# Generated by Django 3.0.8 on 2020-07-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_crud', '0002_auto_20200722_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
