# Generated by Django 3.0.8 on 2020-07-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_crud', '0004_auto_20200722_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
