# Generated by Django 3.0.8 on 2020-07-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_crud', '0005_auto_20200723_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
